COLUMN_MAPPING = {
    'spare_part_id': "int",
    'part_name': "text",
    'description': "text",
    'manufacturer': "text",
    'part_number': "part_number",
    'quantity_in_stock': "positive_int",
    'purchase_price': "float",
    'selling_price': "float",
    'compatible_devices': "text",
    'client_id': "int",
    'first_name': "name",
    'last_name': "name",
    'phone_number': "phone",
    'email': "email",
    'address': "text",
    'notes': "text",
    'order_id': "int",
    'device_id': "int",
    'employee_id': "int",
    'assigned_employee_id': "int",
    'status_id': "int",
    'date_created': "datetime",
    'date_completed': "datetime",
    'problem_description': "text",
    'diagnosis': "text",
    'total_price': "float",
    'quantity_used': "positive_int",
    'price_per_unit': "float",
    'device_type_id': "int",
    'brand': "text",
    'model': "text",
    'serial_number': "serial_number",
    'position': "text",
    'hire_date': "date",
    'is_active': "boolean",
    'service_id': "int",
    'service_name': "text",
    'price': "float",
    'is_hardware': "boolean",
    'type_name': "text",
    'status_name': "text",
    'role_id': "int",
    'role_name': "text",
    'user_id': "int",
    'login': "login",
    'password_hash': "any",
}
COLUMN_NAMES = {
    'spare_part_id': 'ID запчасти',
    'part_name': 'Название запчасти',
    'description': 'Описание',
    'manufacturer': 'Производитель',
    'part_number': 'Номер запчасти',
    'quantity_in_stock': 'Кол-во на складе',
    'purchase_price': 'Цена закупки',
    'selling_price': 'Цена продажи',
    'compatible_devices': 'Совместимые устр.',
    'client_id': 'ID клиента',
    'first_name': 'Имя',
    'last_name': 'Фамилия',
    'phone_number': 'Номер телефона',
    'email': 'Эл. почта',
    'address': 'Адрес',
    'notes': 'Заметки',
    'order_id': 'ID заказа',
    'device_id': 'ID устройства',
    'employee_id': 'ID сотрудника',
    'assigned_employee_id': 'Назнач. сотрудник',
    'status_id': 'ID статуса',
    'date_created': 'Дата создания',
    'date_completed': 'Дата завершения',
    'problem_description': 'Описание проблемы',
    'diagnosis': 'Диагноз',
    'total_price': 'Общая цена',
    'quantity_used': 'Использ. кол-во',
    'price_per_unit': 'Цена за единицу',
    'device_type_id': 'ID типа устр.',
    'brand': 'Бренд',
    'model': 'Модель',
    'serial_number': 'Серийный номер',
    'position': 'Должность',
    'hire_date': 'Дата найма',
    'is_active': 'Активен',
    'service_id': 'ID услуги',
    'service_name': 'Название услуги',
    'price': 'Цена',
    'is_hardware': 'Аппаратное',
    'type_name': 'Тип устройства',
    'status_name': 'Название статуса',
    'role_id': 'ID роли',
    'role_name': 'Название роли',
    'user_id': 'ID юзера',
    'login': 'логин',
    'password_hash': 'хеш пароля',
}
TABLES = {
    "clients": {
        "name": "Клиенты", 
        "label_on_choose": ['first_name', 'last_name'],
        "view_columns": "clients.client_id, clients.first_name, clients.last_name, clients.phone_number, clients.email, clients.address, clients.notes",
        "nessesary_columns": ['first_name', 'last_name'],
        "passed_columns": ['client_id'],
        "join_tables": [],
    },
    "devices": {
        "name": "Устройства", 
        "label_on_choose": ['device_type_id', "serial_number"],
        "view_columns": "devices.device_id, devices.brand, devices.model, devices.serial_number, devices.description, device_types.type_name",
        "nessesary_columns": ['device_type_id', 'brand', 'model'],
        "passed_columns": ['device_id'],
        "join_tables": [{
                "referenced_table_name": "device_types",
                "referenced_column_name": "device_type_id",
                "column_name": "device_type_id"
            }
        ],
    },
    "device_types": {
        "name": "Типы устройств", 
        "label_on_choose": ['type_name'],
        "view_columns": "device_types.device_type_id, device_types.type_name",
        "nessesary_columns": ['type_name'],
        "passed_columns": ['device_type_id'],
        "join_tables": [],
    },
    "employees": {
        "name": "Сотрудники", 
        "label_on_choose": ['first_name', 'last_name'],
        "view_columns": "employees.employee_id, employees.first_name, employees.last_name, employees.position, employees.phone_number, employees.email, employees.hire_date, employees.is_active",
        "nessesary_columns": ['first_name', 'last_name', 'position', 'hire_date'],
        "passed_columns": ['employee_id'],
        "join_tables": [],
    },
    "order_spare_parts": {
        "name": "Заказы запчастей", 
        "label_on_choose": ['order_id', 'spare_part_id', 'quantity_used', 'price_per_unit'],
        "view_columns": "order_spare_parts.order_id, order_spare_parts.spare_part_id, order_spare_parts.quantity_used, order_spare_parts.price_per_unit, spare_parts.part_name",
        "nessesary_columns": ['order_id', 'spare_part_id', 'quantity_used', 'price_per_unit'],
        "passed_columns": [],
        "join_tables": [{
                "referenced_table_name": "spare_parts",
                "referenced_column_name": "spare_part_id",
                "column_name": "spare_part_id"
            }
        ],
    },
    "order_services": {
        "name": "Заказы услуг", 
        "label_on_choose": ['order_id', 'service_id', 'price'],
        "view_columns": "order_services.order_id, order_services.service_id, order_services.price, services.service_name",
        "nessesary_columns": ['order_id', 'service_id', 'price'],
        "passed_columns": [],
        "join_tables": [{
                "referenced_table_name": "services",
                "referenced_column_name": "service_id",
                "column_name": "service_id"
            }
        ],
    },
    "statuses": {
        "name": "Статусы", 
        "label_on_choose": ["status_name"],
        "view_columns": "statuses.status_id, statuses.status_name",
        "nessesary_columns": ['status_name'],
        "passed_columns": ['status_id'],
        "join_tables": [],
    },
    "spare_parts": {
        "name": "Запчасти", 
        "label_on_choose": ["spare_part_id, part_name"],
        "view_columns": "spare_parts.spare_part_id, spare_parts.part_name, spare_parts.description, spare_parts.manufacturer, spare_parts.part_number, spare_parts.quantity_in_stock, spare_parts.purchase_price, spare_parts.selling_price, spare_parts.compatible_devices",
        "nessesary_columns": ['part_name', 'quantity_in_stock', 'purchase_price', 'selling_price'],
        "passed_columns": ['spare_part_id'],
        "join_tables": [],
    },
    "services": {
        "name": "Услуги", 
        "label_on_choose": ["service_name"],
        "view_columns": "services.service_id, services.service_name, services.description, services.price, services.is_hardware",
        "nessesary_columns": ['service_name', 'price'],
        "passed_columns": ['service_id'],
        "join_tables": [],
    },
    "orders": {
        "name": "Заказы", 
        "label_on_choose": ["order_id, problem_description"],
        "view_columns": "orders.order_id, orders.problem_description, orders.diagnosis, orders.total_price, orders.notes, clients.first_name, clients.last_name, devices.brand, devices.model, employees.first_name, employees.last_name, statuses.status_name, orders.date_created",
        "nessesary_columns": ['client_id', 'device_id', 'employee_id', 'status_id', 'date_created', 'total_price'],
        "passed_columns": ['order_id', 'date_created'],
        "join_tables": [{
                "referenced_table_name": "clients",
                "referenced_column_name": "client_id",
                "column_name": "client_id"
            },{
                "referenced_table_name": "devices",
                "referenced_column_name": "device_id",
                "column_name": "device_id"
            },{
                "referenced_table_name": "employees",
                "referenced_column_name": "employee_id",
                "column_name": "employee_id"
            },{
                "referenced_table_name": "statuses",
                "referenced_column_name": "status_id",
                "column_name": "status_id"
            }
        ],
    },
}